### ISSUE TITLE
:bulb: Switching Build to poetry :grey_question: 

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#158]

**Comment by hugovk** [comment]
Why?

**Comment by adriens** [comment]
> Why?

Why not ;-p

More seriously because it may be easier to maintain and produce wheel and other cool stuf without any effort.

It was just an idea. I gave it a try (as a Python noob) and could build/release package very easily.

**Comment by hugovk** [comment]
Thanks for the suggestion! 

Hatchling is also easy to maintain, and I have automation to:

* Draft releases from merged PRs using labels matching https://keepachangelog.com
* Automatically select the next version number based on SemVer changes
* Part of this is due to the hatch_vcs plugin that takes the version number from the Git tag
* Create source distribution and wheel files on the CI, and upload them directly to PyPI
* Two-click release process: edit the draft, click "Publish". Means I can release using my phone :)

For a long time there was really only option for Python (setuptools), but now things have improved and there's lots of choices (if you don't have C/C++ extensions). That means choosing which to use is the difficult thing :)  Many are excellent, so it doesn't really matter which you use. I like hatchling because it's following standards, the maintainer is very helpful, and because of the hatch_vcs plugin.

**Comment by adriens** [comment]
I had never heard of [`pypa/hatch`](https://github.com/pypa/hatch) : thanks a lot for the tip :pray:

**Comment by hugovk** [comment]
See also https://packaging.python.org/en/latest/tutorials/packaging-projects/ and https://www.pyopensci.org/python-package-guide/package-structure-code/intro.html for some more options.

**Comment by adriens** [comment]
:ok_hand:
